- name: Converge
  hosts: all

  pre_tasks:
  - name: Standard apt setup
    become: true
    apt:
      update_cache: yes
      cache_valid_time: 600
    when: ansible_os_family == 'Debian'

  vars:
  - run_tests: false

  roles:
  - role: "marvel-nccr.wannier90"
