---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      become: true
      apt:
        name:
        - software-properties-common
        - git
        update_cache: yes 
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  vars:
    - run_tests: true

  roles:
    - role: "marvel-nccr.wannier90"
